/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PRUEBAS;

import Conexion.conexion;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Garcia
 */
public class REGISTROCAMIONES extends javax.swing.JDialog {

    /**
     * Creates new form REGISTROCAMIONES
     */
    public REGISTROCAMIONES(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        estado.setVisible(false);
        lblestado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcapacidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnum_control = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnum_serie = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtpropietario = new javax.swing.JTextField();
        lblestado = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setText("Numero de control interno");

        txtmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmodeloKeyTyped(evt);
            }
        });

        txtcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcolorKeyTyped(evt);
            }
        });

        jLabel5.setText("Placa");

        txtcapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcapacidadKeyTyped(evt);
            }
        });

        jLabel6.setText("Número de Identificación Vehicular (NIV)");

        jLabel3.setText("Marca");

        jLabel4.setText("Color");

        jLabel2.setText("Modelo (4 digitos)");

        jLabel9.setText("Capacidad (toneladas)");

        txtnum_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnum_serieKeyTyped(evt);
            }
        });

        txtplaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtplacaFocusLost(evt);
            }
        });
        txtplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtplacaKeyTyped(evt);
            }
        });

        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel10.setText("Propietario");

        txtpropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpropietarioKeyTyped(evt);
            }
        });

        lblestado.setText("Estado:");

        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activado", "Reparacion", "Eliminado" }));
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnum_serie)
                    .addComponent(txtplaca)
                    .addComponent(txtcolor)
                    .addComponent(txtmodelo)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(txtmarca)
                    .addComponent(jLabel3)
                    .addComponent(txtnum_control)
                    .addComponent(jLabel8)
                    .addComponent(txtpropietario)
                    .addComponent(jLabel10)
                    .addComponent(txtcapacidad)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblestado)
                        .addGap(26, 26, 26)
                        .addComponent(estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(txtnum_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(txtnum_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(txtpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblestado)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodeloKeyTyped
        char caracter = evt.getKeyChar();
        if(txtmodelo.getText().length()>3){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        if(caracter < '0' || caracter > '9' && caracter != KeyEvent.VK_BACK_SPACE){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtmodeloKeyTyped

    private void txtcolorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcolorKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcolorKeyTyped

    private void txtcapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcapacidadKeyTyped
        char caracter = evt.getKeyChar();
        if(txtcapacidad.getText().length()>1){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        if(caracter < '0' || caracter > '9' && caracter != KeyEvent.VK_BACK_SPACE){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcapacidadKeyTyped

    private void txtnum_serieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnum_serieKeyTyped
        if(txtnum_serie.getText().length()>15){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9' && caracter != KeyEvent.VK_BACK_SPACE &&((caracter<'a' || caracter>'z') && (caracter<'A' || caracter>'Z')) ){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtnum_serieKeyTyped

    private void txtplacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtplacaFocusLost
        String s= txtplaca.getText().toUpperCase();
        if(s.length()>0){
            boolean letra=false;
            int contador = 0;

            if(!(s.charAt(0)<'A' || s.charAt(0)>'Z')){
                letra=true;
            }
            else if(!(s.charAt(0) < '0' || s.charAt(0) > '9')){
            }
            if(letra){
                int numletras=1,numero=0;
                for (int i = 1; i < s.length(); i++) {
                    if(!(s.charAt(i)<'A' || s.charAt(i)>'Z')){
                        numletras++;
                    }
                    if(!(s.charAt(i) < '0' || s.charAt(i) > '9')){
                        numero++;
                    }
                    if(s.charAt(i)=='-' && (s.charAt(3)== '-' && s.charAt(6)=='-')){
                        contador++;
                    }
                }
                if(contador!=2 || numletras != 3 || txtplaca.getText().length() != 9 || numero != 4)
                {
                    errorplaca=true;
//                    JOptionPane.showMessageDialog(this, "Error de placa");
//                    txtplaca.requestFocus();
                }
            }
            else{
                int numero=1, numletras=0;
                for (int i = 1; i < s.length(); i++) {
                    if(!(s.charAt(i) < '0' || s.charAt(i) > '9')){
                        numero++;
                    }
                    if(!(s.charAt(i)<'A' || s.charAt(i)>'Z')){
                        numletras++;
                    }
                    if(s.charAt(i)=='-' && (s.charAt(2)== '-' && s.charAt(5)=='-')){
                        contador++;
                    }
                }
                if(contador!=2  || numero != 4 || txtplaca.getText().length() != 9 || numletras != 3)
                {
                    errorplaca=true;
//                    JOptionPane.showMessageDialog(this, "Error de  formato placa");
//                    txtplaca.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txtplacaFocusLost

    private void txtplacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplacaKeyTyped
        // TODO add your handling code here:
        if(txtplaca.getText().length()>8)
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtplacaKeyTyped

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!modificar){
            boolean error = true;
            String campo = "";
            if (txtmarca.getText().equals("") || txtmarca.getText().length() < 5) {
                error = false;
                campo = "modelo";
            }
            if (txtmodelo.getText().equals("")) {
                error = false;
                campo += "\nmarca";
            }
            if (txtcolor.getText().equals("")) {
                error = false;
                campo += "\ncolor";
            }
            if (txtplaca.getText().equals("") || !error) {
                error = false;
                campo += "\nplaca";
            }
            if (txtnum_serie.getText().equals("")) {
                error = false;
                campo += "\nnumero de serie";
            }
            if (txtnum_control.getText().equals("")) {
                error = false;
                campo += "\nnumero de control interno";
            }
            if (txtcapacidad.getText().equals("")) {
                error = false;
                campo += "\ncapacidad";
            }
            if (txtpropietario.getText().equals("")) {
                error = false;
                campo += "\npropietario";
            }
            if (error) {
                conexion consql = new conexion();

                Statement stat = consql.conectar();
                if (stat != null) {
                    if (consql.ejecutarSQL("INSERT INTO tb_camion(marca,modelo,color,no_placa,no_serie,no_control,capacidad,propietario,estatus_id)VALUES('" + txtmarca.getText() + "','" + txtmodelo.getText() + "','" + txtcolor.getText() + "','" + txtplaca.getText() + "','" + txtnum_serie.getText() + "','" + txtnum_control.getText() + "','" + txtcapacidad.getText() + "','" + txtpropietario.getText() + "',1);")) {
                        JOptionPane.showMessageDialog(this, "Ok se inserto");
                        //                System.out.println("inserto");
                        registrook = true;
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, "Error");
                        registrook = false;
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error al realizar la conexion");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Corriga los campos:\n" + campo);
            }
        }
        if(modificar){
            conexion consql = new conexion();
            System.err.println(status);
                Statement stat = consql.conectar();
                if (stat != null) {
                    if (consql.ejecutarSQL("UPDATE tb_camion SET marca='"+txtmarca.getText()+"',modelo='"+txtmodelo.getText()+"',color='"+txtcolor.getText()+"',no_placa='"+txtplaca.getText()+"',no_serie='"+txtnum_serie.getText()+"',no_control='"+txtnum_control.getText()+"',capacidad='"+txtcapacidad.getText()+"',propietario='"+txtpropietario.getText()+"',estatus_id='"+status+"' WHERE id='"+id+"';")) {
                        JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente");
                        this.dispose();
                        modif=true;
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "No se pudo guardar los datos");                        
                        modif=false;
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error al realizar la conexion");
                }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtpropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpropietarioKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z') && car!=KeyEvent.VK_SPACE){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtpropietarioKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
       if(estado.getSelectedItem().toString().equals("Activado")){
           status=1;
       }
       if(estado.getSelectedItem().toString().equals("Reparacion")){
           status=2;
       }
       else{
           status=3;
       }
    }//GEN-LAST:event_estadoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(REGISTROCAMIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(REGISTROCAMIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(REGISTROCAMIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(REGISTROCAMIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                REGISTROCAMIONES dialog = new REGISTROCAMIONES(new javax.swing.JDialog(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    public void cargarDatos(){
        modificar=true;
        estado.setVisible(true);
        lblestado.setVisible(true);
        conexion conectar = new conexion();
        Statement st= conectar.conectar();
        String sql="SELECT * FROM tb_camion where id="+id;
        ResultSet rs=conectar.ejecutarSQLSelect(sql);
        if(rs!=null){
            try {
                while(rs.next()){
                    txtmarca.setText(rs.getString("marca"));
                    txtmodelo.setText(rs.getString("modelo"));
                    txtcolor.setText(rs.getString("color"));
                    txtplaca.setText(rs.getString("no_placa"));
                    txtnum_serie.setText(rs.getString("no_serie"));
                    txtnum_control.setText(rs.getInt("no_control")+"");
                    txtcapacidad.setText(rs.getInt("capacidad")+"");
                    txtpropietario.setText(rs.getString("propietario"));
                    if(rs.getInt("estatus_id") == 1){
                        estado.setSelectedIndex(0);
                        status=1;
                    }
                    else if(rs.getInt("estatus_id") == 2){
                        estado.setSelectedIndex(1);
                        status=2;
                    }
                    else{
                        estado.setSelectedIndex(2);
                        status=3;
                    }
                    }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error al consultar");
        }        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox estado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblestado;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnum_control;
    private javax.swing.JTextField txtnum_serie;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtpropietario;
    // End of variables declaration//GEN-END:variables
    public boolean registrook, modificar=false, modif;
    private boolean errorplaca=false;
    private int status=0;
    public int id;
}
