/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import Conexion.conexion;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Garcia
 */
public class registroCamiones extends javax.swing.JDialog {

    /**
     * Creates new form registroCamiones
     */
    public registroCamiones(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Registro de Camiones");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtmarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        txtnum_serie = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        txtnum_control = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcapacidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpropietario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });

        jLabel2.setText("Modelo (4 digitos)");

        jLabel3.setText("Marca");

        jLabel4.setText("Color");

        jLabel5.setText("Placa");

        jLabel6.setText("Número de Identificación Vehicular (NIV)");

        txtmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmodeloKeyTyped(evt);
            }
        });

        txtcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcolorKeyTyped(evt);
            }
        });

        txtnum_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnum_serieKeyTyped(evt);
            }
        });

        txtplaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtplacaFocusLost(evt);
            }
        });
        txtplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtplacaKeyTyped(evt);
            }
        });

        jLabel8.setText("Numero de control interno");

        txtcapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcapacidadKeyTyped(evt);
            }
        });

        jLabel9.setText("Capacidad (toneladas)");

        txtpropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpropietarioKeyTyped(evt);
            }
        });

        jLabel10.setText("Propietario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnum_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnum_control, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(txtnum_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(txtnum_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(txtpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        clickGuardar();
//        boolean error=true;
//        String campo = "";
//        if(txtmarca.getText().equals("") || txtmarca.getText().length()<5){
//            error=false;
//            campo="modelo";
//        }
//        if(txtmodelo.getText().equals("")){
//            error=false;
//            campo+="\nmarca";
//        }
//        if(txtcolor.getText().equals("")){
//            error=false;
//            campo+="\ncolor";
//        }
//        if(txtplaca.getText().equals("")){
//            error=false;
//            campo+="\noplaca";
//        }
//        if(txtnum_serie.getText().equals("")){
//            error=false;
//            campo+="\nnumero de serie";
//        }
//        if(txtnum_control.getText().equals("")){
//            error=false;
//            campo+="\nnumero de control interno";
//        }
//        if(txtcapacidad.getText().equals("")){
//            error=false;
//            campo+="\ncapacidad";
//        }
//        if(txtpropietario.getText().equals("")){
//            error=false;
//            campo+="\npropietario";
//        }        
//        if(error){
//                conexion consql = new conexion();
//
//                Statement stat = consql.conectar();
//                if(stat!=null){
//                    if(consql.ejecutarSQL("INSERT INTO tb_camion(marca,modelo,color,no_placa,no_serie,no_control,capacidad,propietario,estatus_id)VALUES('"+txtmarca.getText()+"','"+txtmodelo.getText()+"','"+txtcolor.getText()+"','"+txtplaca.getText()+"','"+txtnum_serie.getText()+"','"+txtnum_control.getText()+"','"+txtcapacidad.getText()+"','"+txtpropietario.getText()+"',1);")){
//                        JOptionPane.showMessageDialog(this, "Ok se inserto");
//                        //                System.out.println("inserto");
//                        this.dispose();
//                    }
//                    else{
//                        JOptionPane.showMessageDialog(this, "Error");
//                    }
//                }
//            }
//            
//            else{
//                JOptionPane.showMessageDialog(this, "Corriga los campos:\n"+campo);
//            }
        
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    public void clickGuardar(){
        boolean error=true;
        String campo = "";
        if(txtmarca.getText().equals("") || txtmarca.getText().length()<4){
            error=false;
            campo="marca";
        }
        if(txtmodelo.getText().equals("")){
            error=false;
            campo+="\nmodelo";
        }
        if(txtcolor.getText().equals("")){
            error=false;
            campo+="\ncolor";
        }
        if(txtplaca.getText().equals("")){
            error=false;
            campo+="\noplaca";
        }
        if(txtnum_serie.getText().equals("")){
            error=false;
            campo+="\nnumero de serie";
        }
        if(txtnum_control.getText().equals("")){
            error=false;
            campo+="\nnumero de control interno";
        }
        if(txtcapacidad.getText().equals("")){
            error=false;
            campo+="\ncapacidad";
        }
        if(txtpropietario.getText().equals("")){
            error=false;
            campo+="\npropietario";
        }        
        if(error){
                conexion consql = new conexion();

                Statement stat = consql.conectar();
                if(stat!=null){
                    if(consql.ejecutarSQL("INSERT INTO tb_camion(marca,modelo,color,no_placa,no_serie,no_control,capacidad,propietario,estatus_id)VALUES('"+txtmarca.getText()+"','"+txtmodelo.getText()+"','"+txtcolor.getText()+"','"+txtplaca.getText()+"','"+txtnum_serie.getText()+"','"+txtnum_control.getText()+"','"+txtcapacidad.getText()+"','"+txtpropietario.getText()+"',1);")){
                        JOptionPane.showMessageDialog(this, "Ok se inserto");
                        //                System.out.println("inserto");
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
            }
            
            else{
                JOptionPane.showMessageDialog(this, "Corriga los campos:\n"+campo);
            }
    }
    
    private void txtmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodeloKeyTyped
        char caracter = evt.getKeyChar();
        if(txtmodelo.getText().length()>3){            
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        if(caracter < '0' || caracter > '9' && caracter != KeyEvent.VK_BACK_SPACE){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtmodeloKeyTyped

    private void txtcolorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcolorKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcolorKeyTyped

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void txtplacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplacaKeyTyped
        // TODO add your handling code here:
        if(txtplaca.getText().length()>8)
        {
            evt.consume();
        }
            
    }//GEN-LAST:event_txtplacaKeyTyped
    private void txtplacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtplacaFocusLost
        String s= txtplaca.getText().toUpperCase();
        if(s.length()>0){
            boolean letra=false;
            int contador = 0;

            if(!(s.charAt(0)<'A' || s.charAt(0)>'Z')){
                letra=true;
            }
            else if(!(s.charAt(0) < '0' || s.charAt(0) > '9')){            
            }        
            if(letra){
                int numletras=1,numero=0;
                for (int i = 1; i < s.length(); i++) {
                    if(!(s.charAt(i)<'A' || s.charAt(i)>'Z')){
                        numletras++;
                    }
                    if(!(s.charAt(i) < '0' || s.charAt(i) > '9')){
                        numero++;
                    }
                    if(s.charAt(i)=='-' && (s.charAt(3)== '-' && s.charAt(6)=='-')){
                        contador++;
                    }
                }            
                if(contador!=2 || numletras != 3 || txtplaca.getText().length() != 9 || numero != 4)
                {
                    JOptionPane.showMessageDialog(this, "Error de placa");
                    txtplaca.requestFocus();
                }
            }
            else{
                int numero=1, numletras=0;
                for (int i = 1; i < s.length(); i++) {
                     if(!(s.charAt(i) < '0' || s.charAt(i) > '9')){
                        numero++;
                    }                
                    if(!(s.charAt(i)<'A' || s.charAt(i)>'Z')){
                        numletras++;
                    }
                    if(s.charAt(i)=='-' && (s.charAt(2)== '-' && s.charAt(5)=='-')){
                        contador++;
                    }
                }
                if(contador!=2  || numero != 4 || txtplaca.getText().length() != 9 || numletras != 3)
                {
                    JOptionPane.showMessageDialog(this, "Error de  formato placa");
                    txtplaca.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txtplacaFocusLost

    private void txtnum_serieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnum_serieKeyTyped
        if(txtnum_serie.getText().length()>15){            
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9' && caracter != KeyEvent.VK_BACK_SPACE &&((caracter<'a' || caracter>'z') && (caracter<'A' || caracter>'Z')) ){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtnum_serieKeyTyped

    private void txtcapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcapacidadKeyTyped
        char caracter = evt.getKeyChar();
        if(txtcapacidad.getText().length()>1){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        if(caracter < '0' || caracter > '9' && caracter != KeyEvent.VK_BACK_SPACE){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtcapacidadKeyTyped

    private void txtpropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpropietarioKeyTyped
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtpropietarioKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(registroCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(registroCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(registroCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(registroCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                registroCamiones dialog = new registroCamiones(new javax.swing.JDialog(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnum_control;
    private javax.swing.JTextField txtnum_serie;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtpropietario;
    // End of variables declaration//GEN-END:variables
}
